version: '3.8'

services:
  web:
    image: diamol/ch06-todo-list
    ports:
      - "80:80"
    restart: always

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: todo
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
